# Generated by Django 2.1 on 2018-11-03 01:16

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('file_one', models.FileField(upload_to='upload/%Y/%m/%d/')),
                ('portaint', models.FileField(upload_to=polls.models.get_portaint_path)),
            ],
        ),
    ]
